pipeline {
    agent any

    stages {

        stage('Echo') {
            steps {
                echo "Echoing a message to demonstrate Jenkins pipeline execution."
                echo "Step 2"
            }
        }

    }
}
